// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-EceUvrWT9FHUZdxnptN1hjf0vXYehso',
    appId: '1:207579616932:web:0abfedaf58bcbaa07f3831',
    messagingSenderId: '207579616932',
    projectId: 'chatting-application-35ab6',
    authDomain: 'chatting-application-35ab6.firebaseapp.com',
    storageBucket: 'chatting-application-35ab6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4aK90GOng3YQUGfoTHTnOKM00iij8F0Y',
    appId: '1:207579616932:android:8e5311a92e1d9c207f3831',
    messagingSenderId: '207579616932',
    projectId: 'chatting-application-35ab6',
    storageBucket: 'chatting-application-35ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2szRLp49z672MGTZLh3XMG3tJC6tlwE4',
    appId: '1:207579616932:ios:a5a2dd59226883447f3831',
    messagingSenderId: '207579616932',
    projectId: 'chatting-application-35ab6',
    storageBucket: 'chatting-application-35ab6.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2szRLp49z672MGTZLh3XMG3tJC6tlwE4',
    appId: '1:207579616932:ios:a5a2dd59226883447f3831',
    messagingSenderId: '207579616932',
    projectId: 'chatting-application-35ab6',
    storageBucket: 'chatting-application-35ab6.firebasestorage.app',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-EceUvrWT9FHUZdxnptN1hjf0vXYehso',
    appId: '1:207579616932:web:4d7291bc3cd5b1ca7f3831',
    messagingSenderId: '207579616932',
    projectId: 'chatting-application-35ab6',
    authDomain: 'chatting-application-35ab6.firebaseapp.com',
    storageBucket: 'chatting-application-35ab6.firebasestorage.app',
  );
}
